### ISSUE TITLE
TODO List for the core Rewrite.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/Universal-Core#1]
- [ ] Add HID handling to Universal-Core.

- [ ] Improve current core with GUI and more.

More probably too, but I don't have more Things in my mind rn.

**Comment by SuperSaiyajinStackZ** [comment]
If someone likes to help, feel free to contribute to the core-rewrite branch.

**Comment by SuperSaiyajinStackZ** [comment]
OK, as of the latest commit, HID is initial implemented. There might be broken stuff, but I'll figure it out later.

**Comment by SuperSaiyajinStackZ** [comment]
If anyone has feature requests for Universal-Core, then comment under this issue! The GUI part seems to be good and HID as well (but it's not really used I think.) I will work on the wiki for Universal-Core in the coming days, so you can always look at the functions there!

**Comment by ghost** [comment]
I gonna link this issue here. I'm not sure if that's related to Universal-Core right now.

[[Bug Report] Crash when trying to exit `Get Scripts`.](https://github.com/Universal-Team/Universal-Updater/issues/31)

**Comment by ghost** [comment]
The crash on Universal-Updater was unrelated to Universal-Core. I forgot to call `return;` after `Gui::screenBack(bool fade);`.
